version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  qdrant:
    image: qdrant/qdrant:v1.13.6
    container_name: qdrant_locally
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  app:  # Add FastAPI app service here
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"  # Expose FastAPI app on port 8000
    depends_on:
      - postgres
      - qdrant

volumes:
  postgres_data:
    driver: local
  qdrant_data:
    driver: local
