name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: '${{ vars.PROJECT_ID }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v2
        # with:
        #   project_id: ${{ env.PROJECT_ID }}
          # service_account_key: ${{ secrets.GCP_CREDENTIALS }} # credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          # export_default_credentials: true

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy data-ingestion \
            --gen2 \
            --runtime python312 \
            --entry-point data_ingestion \
            --source ./src/core \
            --region europe-west1
       

      # - name: Deploy Cloud Function
      #   id: deploy
      #   uses: google-github-actions/deploy-cloud-functions@v2
      #   with:
      #     name: data-ingestion
      #     runtime: python313
      #     source: ./src/core
      #     entry_point: data_ingestion.py
      #     event_trigger_type: providers/cloud.storage/eventTypes/object.finalize
      #     event_trigger_resource: projects/_/buckets/eam-meetings/objects/*.docx

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding data-ingestion --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"

