name: Run Shell Script

on:
  push:
    branches:
      - main  # Trigger the action on a push to the main branch (adjust as needed)
 
jobs:
  run_script:
    runs-on: ubuntu-latest  # Using an Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug: Print the secret value before saving to file
      run: |
        echo "SET_VARS secret: $SET_VARS"  # Debugging step to see if the secret is loaded
      env:
        SET_VARS: ${{ secrets.SET_VARS }}  # Access the set_Vars secret 