name: Run Shell Script

on:
  push:
    branches: [ main ]
 
jobs:
  run_script:
    runs-on: ubuntu-latest  # Using an Ubuntu runner

    steps:
      - uses: actions/checkout@v4
      
      # Decode .env file (creates it in runner's workspace)
      - name: Create .env file
        run: echo "${{ secrets.SET_VARS1 }}" | base64 --decode > .env
             echo "QDRANT_URL=$QDRANT_URL"
 